#!/bin/bash
#
#  Copyright 2011 richard.hierlmeier@web.de.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  under the License.
if [ -L $0 ]; then
   SCRIPT=`ls -l $0 | sed 's/^.*-> //'`
else
   SCRIPT=$0
fi
# Absolute path this script is in. /home/user/bin
BASEDIR=`dirname $SCRIPT`

java -jar $BASEDIR/JWhich.jar $*
